auth0:
  domain: auth.hivemq.cloud
  client-id: 5t8lB7digowuiKZaV6rPOGIxiZARNn4S
  audience: hivemq-cloud-api
  scope: openid profile email offline_access

fallback:
  org-id: "dummy"
  pulse-base-url: "https://pulse2.dev.hmqc.dev"
  agentx-base-url: "https://act.hivemq.com"
  console-base-url: "https://api.console.hivemq.cloud"
